# -*- coding: utf-8 -*-
"""KCV_Dysarthria.ipynb

Automatically generated by Colab.

## **Automatic Detection of Dysarthria Using CNN on Acoustic Speech Data**

## IMPORT MODULES
"""

import kagglehub                     # ambil dataset dri kaggle
import numpy as np                   # operasi numerik/array
import pandas as pd                  # manipulaso data tabular
import os                            # navigasi file sistem
import re                            
import warnings                        
import matplotlib.pyplot as plt      # visualisasi grafik
import seaborn as sns                # visualisasi statistik
import librosa                       # untuk audio processing
import librosa.display               # untuk menampilkn waveform, spectogram, dll
import IPython.display as ipd        # untuk putar audio langsung di notebook
from sklearn.preprocessing import minmax_scale    # normalisasi nilai ke rentang [0, 1]

# feature extraction
from tqdm import tqdm                                    # progress bar saat looping
from sklearn.preprocessing import StandardScaler         
from sklearn.model_selection import train_test_split     
from sklearn.metrics import (
    classification_report,   # laporan precision, recall, f1 per kelas
    confusion_matrix,        # matriks confusion untuk evaluasi visual
    roc_auc_score,           # skor AUC dari kurva ROC
    roc_curve,               # menghitung titik-titik kurva ROC
    recall_score             # recall score keseluruhan
)
# modelling CNN-GRU
import tensorflow as tf
from tensorflow.keras.models import Sequential # layar ditumpuk satu satu, model sequential
from tensorflow.keras.layers import (
    InputLayer,         # mendefinisikan bentuk input
    Conv2D,             # layer konvolusi 2D untuk ekstraksi fitur spasial
    MaxPooling2D,       # downsampling / memperkecil dimensi
    BatchNormalization, # normalisasi batch agar training lebih stabil
    Reshape,            # mengubah bentuk tensor (dari 2D ke sekuens untuk GRU)
    GRU,                # Gated Recurrent Unit untuk menangkap pola temporal
    Dense,              # fully connected layer
    Dropout             # regularisasi: matikan sebagian neuron secara acak saat training
)
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint # callback saat training
from tensorflow.keras.metrics import AUC, Precision, Recall           # mettrik evaluasi tambahan

plt.rcParams['figure.figsize'] = (20,8)    # ukuran default semua plot
plt.rcParams['font.size'] = 16             # ukuran font default
sns.set_style('darkgrid')                  # tema seaborn
warnings.filterwarnings("ignore")          # sembunyikan warning agar output lebih bersih

"""## LOAD DATASET"""

# Download dataset TORGO dari Kaggle
# Dataset ini berisi rekaman suara speaker dysarthria dan non-dysarthria
path = kagglehub.dataset_download("iamhungundji/dysarthria-detection")
os.listdir(path + "/torgo_data") # cek isi folder dataset

# Baca file CSV yang berisi metadata: nama file audio, label, dan gender
df = pd.read_csv(path + "/torgo_data/data.csv")

# Tambahkan path lengkap ke kolom filename supaya bisa di-load langsung
df['filename'] = df['filename'].apply(lambda x: path + "/" + x)

print(f"Total samples: {len(df)}")
print(f"Columns      : {df.columns.tolist()}")
df.head()

"""## EDA"""

# cek tipe data dan ada tidaknya nilai kosong
print(df.info())
print()
print(df.describe())

# --- Plot 1: Distribusi label dan gender ---
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Dysarthria label counts
df['is_dysarthria'].value_counts().plot(kind='bar', ax=axes[0], color=['steelblue','salmon'], edgecolor='black')
axes[0].set_title('Dysarthria Label Distribution')
axes[0].set_xlabel('Label')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=0)

# Gender counts
df['gender'].value_counts().plot(kind='bar', ax=axes[1], color=['mediumpurple','coral'], edgecolor='black')
axes[1].set_title('Gender Distribution')
axes[1].set_xlabel('Gender')
axes[1].set_ylabel('Count')
axes[1].tick_params(axis='x', rotation=0)

plt.suptitle('Dataset Overview', fontsize=18, fontweight='bold')
plt.tight_layout()
plt.show()

# Cross-tabulation: Gender × Label
cross = pd.crosstab(df['gender'], df['is_dysarthria'])
print(cross)

cross.plot(kind='bar', figsize=(8, 5), color=['steelblue','salmon'], edgecolor='black')
plt.title('Gender × Dysarthria Label')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.legend(title='Label')
plt.tight_layout()
plt.show()

# Per-group sample preview
groups = {
    'Male   – Dysarthria'    : df[(df['gender']=='male')   & (df['is_dysarthria']=='dysarthria')],
    'Female – Dysarthria'    : df[(df['gender']=='female') & (df['is_dysarthria']=='dysarthria')],
    'Male   – Non-Dysarthria': df[(df['gender']=='male')   & (df['is_dysarthria']=='non_dysarthria')],
    'Female – Non-Dysarthria': df[(df['gender']=='female') & (df['is_dysarthria']=='non_dysarthria')],
}

for name, subset in groups.items():
    print("=" * 55)
    print(f" {name}  (n={len(subset)})")
    print("=" * 55)
    display(subset.head(3))
    print()

"""## FEATURES"""

def show_waveplot(audio_path, label, gender):
    """
    Menampilkan bentuk gelombang (waveform) audio dalam domain waktu.
    Sumbu X = waktu (detik), sumbu Y = amplitudo.
    Suara dysarthria biasanya punya pola amplitudo yang tidak teratur.
    """
    x, sr = librosa.load(audio_path)
    plt.figure(figsize=(20, 6))
    librosa.display.waveshow(x, sr=sr)
    plt.title(f"Waveplot | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Time (s)")
    plt.ylabel("Amplitude")
    plt.tight_layout()
    plt.show()


def show_spectrogram(audio_path, label, gender):
     """
    Menampilkan spektrogram STFT (Short-Time Fourier Transform) dalam skala dB.
    Spektrogram memperlihatkan distribusi energi frekuensi dari waktu ke waktu.
    Warna lebih terang = energi lebih tinggi di frekuensi tersebut.
    """
    x, sr = librosa.load(audio_path)
    X    = librosa.stft(x)    # transformasi fourier pendek
    Xdb  = librosa.amplitude_to_db(abs(X))    # konversi ke skala desibel
    plt.figure(figsize=(20, 6))
    librosa.display.specshow(Xdb, sr=sr, x_axis='time', y_axis='hz', cmap='plasma')
    plt.colorbar(format='%+2.0f dB')
    plt.title(f"Spectrogram | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.tight_layout()
    plt.show()


def show_zcr(audio_path, label, gender):
    """
    Menampilkan Zero Crossing Rate (ZCR)
    seberapa sering sinyal audio melewati nilai nol per frame. ZCR tinggi biasanya menandai suara tak bersuara
    (unvoiced) seperti konsonan 's', 'f'. Dysarthria sering punya pola ZCR berbeda.
    """
    x, sr = librosa.load(audio_path)
    zcrs  = librosa.feature.zero_crossing_rate(x)
    total = librosa.zero_crossings(x).sum()
    print(f"Total zero crossings: {total}")
    plt.figure(figsize=(20, 5))
    plt.plot(zcrs[0], color='teal')
    plt.title(f"Zero Crossing Rate | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Frame")
    plt.ylabel("ZCR")
    plt.tight_layout()
    plt.show()

def show_spectral_centroids(audio_path, label, gender):
    """
    Menampilkan Spectral Centroid , yaitu titik berat dari distribusi frekuensi.
    Nilai tinggi = energi dominan di frekuensi tinggi (suara cerah/terang).
    Nilai rendah = energi dominan di frekuensi rendah (suara gelap/berat).
    Ditumpuk di atas waveform untuk perbandingan.
    """
    x, sr = librosa.load(audio_path)
    spectral_centroids = librosa.feature.spectral_centroid(y=x, sr=sr)[0]
    frames = range(len(spectral_centroids))
    t      = librosa.frames_to_time(frames)
    plt.figure(figsize=(20, 5))
    librosa.display.waveshow(x, sr=sr, alpha=0.4)
    plt.plot(t, normalize(spectral_centroids), color='r')
    plt.title(f"Spectral Centroids | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Time (s)")
    plt.ylabel("Normalized Centroid")
    plt.tight_layout()
    plt.show()


def show_spectral_rolloff(audio_path, label, gender):
    """
    Menampilkan Spectral Rolloff, frekuensi di mana 99% energi spektral
    sudah terkumpul. Berguna untuk membedakan suara voiced vs unvoiced,
    dan bisa menangkap karakteristik artikulasi yang bermasalah pada dysarthria.
    """
    x, sr = librosa.load(audio_path)
    spectral_rolloff = librosa.feature.spectral_rolloff(y=x, sr=sr, roll_percent=0.01)[0]
    frames = range(len(spectral_rolloff))
    t      = librosa.frames_to_time(frames)
    plt.figure(figsize=(20, 5))
    librosa.display.waveshow(x, sr=sr, alpha=0.4)
    plt.plot(t, normalize(spectral_rolloff), color='r')
    plt.title(f"Spectral Rolloff | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Time (s)")
    plt.ylabel("Normalized Rolloff")
    plt.tight_layout()
    plt.show()


def show_mfccs(audio_path, label, gender):
    """
    Menampilkan MFCC (Mel-Frequency Cepstral Coefficients) sebagai heatmap.
    MFCC adalah representasi spektral yang meniru cara telinga manusia mendengar.
    Ini adalah fitur utama yang kami ekstrak untuk training model.
    """
    x, sr = librosa.load(audio_path)
    mfccs = librosa.feature.mfcc(y=x, sr=sr)
    plt.figure(figsize=(20, 6))
    librosa.display.specshow(mfccs, sr=sr, x_axis='time', cmap='plasma')
    plt.colorbar(format='%+2.0f')
    plt.title(f"MFCC | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Time (s)")
    plt.ylabel("MFCC Coefficient")
    plt.tight_layout()
    plt.show()


def show_melspectro(audio_path, label, gender):
    """
    Menampilkan Mel Spectrogram, seperti spektrogram biasa tapi sumbu frekuensinya
    menggunakan skala mel. 
    """
    x, sr      = librosa.load(audio_path)
    melspectro = librosa.feature.melspectrogram(y=x, sr=sr)
    plt.figure(figsize=(20, 6))
    librosa.display.specshow(melspectro, sr=sr, x_axis='time', y_axis='mel', cmap='plasma')
    plt.colorbar(format='%+2.0f dB')
    plt.title(f"Mel Spectrogram | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Time (s)")
    plt.ylabel("Mel Frequency")
    plt.tight_layout()
    plt.show()

def normalize(x, axis=0):
    """Normalisasi nilai ke rentang [0, 1] supaya bisa diplot bersama waveform."""
    return minmax_scale(x, axis=axis)

# Ambil satu sampel dari setiap kombinasi gender × label
sample_dys_female     = df[(df['is_dysarthria'] == 'dysarthria')     & (df['gender'] == 'female')].iloc[105]
sample_dys_male       = df[(df['is_dysarthria'] == 'dysarthria')     & (df['gender'] == 'male')].iloc[32]
sample_non_dys_female = df[(df['is_dysarthria'] == 'non_dysarthria') & (df['gender'] == 'female')].iloc[480]
sample_non_dys_male   = df[(df['is_dysarthria'] == 'non_dysarthria') & (df['gender'] == 'male')].iloc[0]

ipd.Audio(sample_dys_female['filename'])

ipd.Audio(sample_non_dys_female['filename'])

ipd.Audio(sample_dys_male['filename'])

ipd.Audio(sample_non_dys_male['filename'])


# Tampilkan semua visualisasi fitur untuk keempat sampel
for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_waveplot        (sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_spectrogram     (sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_zcr             (sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_spectral_centroids(sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_spectral_rolloff(sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_mfccs           (sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_melspectro      (sample['filename'], sample['is_dysarthria'], sample['gender'])

"""## FEATURES EXTRACTION"""

def feature_extraction(df):
    """
    Ekstrak fitur MFCC dari setiap file audio dalam DataFrame.

    Prosesnya:
    - Load setiap file audio menggunakan librosa
    - Hitung 128 koefisien MFCC
    - Ambil rata-rata (mean) tiap koefisien sepanjang waktu
      → hasilnya vektor 128 angka per sampel audio
    - Simpan juga label kelas dan speaker ID

    Kenapa mean MFCC?
    Karena setiap audio punya durasi berbeda, sehingga jumlah frame-nya
    berbeda-beda. Dengan mengambil mean, kita dapat representasi
    fixed-size (128 dimensi) untuk semua audio.

    Kenapa n_mfcc=128?
    Karena lebih detail dibanding 40, akurasinya juga lebih tinggi
    """
    features = []
    valid_idx = []
    for i, record in tqdm(df.iterrows(), total=df.shape[0]):
        try:
            x, sr = librosa.load(record['filename'])    # load audio, sr default = 22050 Hz
            mean_mfcc = np.mean(librosa.feature.mfcc(y=x, sr=sr, n_mfcc=128), axis=1) # mean per koefisien (bukan per frame)
            features.append(mean_mfcc)
            valid_idx.append(i)
        except EOFError:
            # Skip file yang corrupt atau tidak bisa dibaca
            pass

    dataf = pd.DataFrame(features)
    dataf['class'] = df.loc[valid_idx, 'is_dysarthria'].values
    
    # Ekstrak speaker ID dari nama file, misal: "FC03_Session2..." → "FC03"
    dataf['speaker_id'] = df.loc[valid_idx, 'filename'].str.extract(r'/(F[CM]\d+|MC\d+|FC\d+|M\d+|F\d+)_').values.flatten()
    return dataf

# Jalankan feature extraction untuk seluruh dataset (2000 sampel)
dataf = feature_extraction(df)
dataf


# setiap speaker hanya boleh masuk ke satu split saja untuk hindari data leakage
# sehingga test set berisi suara orang yang belum pernah dilihat model
# Dysarthria speakers    : F01, F03, F04, M01, M02, M03, M04, M05
# Non-dysarthria speakers: FC01, FC02, FC03, MC01, MC02, MC03, MC04
train_speakers = ['F03','F04','M02','M03','M05', 'FC02','FC03','MC01','MC03']
val_speakers   = ['M01','M04',                   'MC02','MC04']
test_speakers  = ['F01',                         'FC01']

# Filter baris berdasarkan speaker ID
train_df = dataf[dataf['speaker_id'].isin(train_speakers)]
val_df   = dataf[dataf['speaker_id'].isin(val_speakers)]
test_df  = dataf[dataf['speaker_id'].isin(test_speakers)]

# Encode label teks ke angka: non_dysarthria=0.0, dysarthria=1.0
for d in [train_df, val_df, test_df]:
    d['class'] = d['class'].map({'non_dysarthria': 0.0, 'dysarthria': 1.0})

# Ambil fitur (128 kolom pertama) dan reshape ke (n, 16, 8, 1)
# Kenapa (16, 8, 1)?
#   - 128 = 16 × 8 → kita anggap MFCC sebagai gambar 16×8 piksel
#   - 1 = channel (grayscale, bukan RGB)
#   - supaya bisa diproses oleh Conv2D yang biasanya menerima input 2D
X_train = train_df.iloc[:, :-2].values.reshape(-1, 16, 8, 1)
X_val   = val_df.iloc[:, :-2].values.reshape(-1, 16, 8, 1)
X_test  = test_df.iloc[:, :-2].values.reshape(-1, 16, 8, 1)

# Ambil kolom label sebagai target
y_train = train_df['class'].values
y_val   = val_df['class'].values
y_test  = test_df['class'].values

# Cek distribusi setiap split
print("Train:", X_train.shape, "| Val:", X_val.shape, "| Test:", X_test.shape)
print("Train label dist:", pd.Series(y_train).value_counts().to_dict())
print("Val label dist  :", pd.Series(y_val).value_counts().to_dict())
print("Test label dist :", pd.Series(y_test).value_counts().to_dict())

"""## MODELLING"""
# Arsitektur yang digunakan adalah kombinasi CNN dan GRU
# Setelah CNN mengekstrak fitur, GRU menangkap hubungan antar-frame
model = Sequential([

    # Input: tensor berukuran (16, 8, 1), MFCC yang sudah di-reshape
    InputLayer(input_shape=(16, 8, 1)),

    # Conv2D: cari pola lokal dalam grid MFCC menggunakan 32 filter 3×3
    # activation='relu': non-linearitas, matikan neuron negatif
    # padding='same': pertahankan ukuran spasial setelah konvolusi
    Conv2D(32, (3, 3), activation='relu', padding="same"),
    BatchNormalization(), # normalisasi output per batch → training lebih stabil & cepat
    MaxPooling2D(2, 2),   # downsample: kurangi dimensi spasial jadi setengah → (8, 4, 32)
    
    # Filter bertambah jadi 64 → fitur yang lebih kompleks dan abstrak
    Conv2D(64, (3, 3), activation='relu', padding="same"),
    BatchNormalization(),
    MaxPooling2D(2, 2), # ukuran jadi (4, 2, 64)

    # Reshape untuk GRU
    # GRU butuh input 2D: (timesteps, features)
    # Kita flatten dimensi terakhir: (4, 2, 64) → (4, 128)
    # Artinya: 4 timestep, masing-masing berisi 128 fitur
    Reshape((4, 128)),
    # 64 unit GRU, return_sequences=False → hanya output dari timestep terakhir
    GRU(64, return_sequences=False),
    # Dropout: saat training, 30% neuron dimatikan secara acak
    Dropout(0.3),

    Dense(32, activation='relu'),    # layer intermediate untuk kombinasi fitur
    Dense(1, activation='sigmoid')    # output: 1 neuron, nilai 0–1
])

# Compile model
# optimizer='adam'           : adaptive learning rate
# loss='binary_crossentropy' : loss function standar untuk klasifikasi biner
# metrics                    : pantau accuracy, AUC, precision, dan recall
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[
        'accuracy',
        AUC(name='auc'), # area under curve
        Precision(name='precision'), 
        Recall(name='recall')
    ]
)

# Simpan model ke file 'model.h5' setiap kali val_loss membaik (turun)
# save_best_only=True → hanya simpan yang terbaik, bukan setiap epoch
model_name = "model.h5"
checkpoint = ModelCheckpoint(model_name,
                            monitor="val_loss",
                            mode="min",
                            save_best_only = True,
                            verbose=1)

# Hentikan training jika val_loss tidak membaik selama 5 epoch berturut-turut
# restore_best_weights=True → kembalikan bobot ke epoch terbaik setelah berhenti
earlystopping = EarlyStopping(
    monitor='val_loss',
    min_delta=0,      # perubahan sekecil apapun dianggap sebagai perbaikan
    patience=5,       # toleransi 5 epoch tanpa perbaikan sebelum berhenti
    verbose=1,
    restore_best_weights=True
)

# Latih model selama maksimal 50 epoch dengan data train & validasi
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_val,y_val), callbacks=[checkpoint,earlystopping])

"""## Model Summary

### Learning Curves
"""

fig, axes = plt.subplots(1, 2, figsize=(20, 6))

axes[0].plot(history.history['loss'],     label='Train Loss')
axes[0].plot(history.history['val_loss'], label='Val Loss')
axes[0].set_title('Loss', fontsize=14)
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].legend()

axes[1].plot(history.history['accuracy'],     label='Train Accuracy')
axes[1].plot(history.history['val_accuracy'], label='Val Accuracy')
axes[1].set_title('Accuracy', fontsize=14)
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Accuracy')
axes[1].legend()

plt.tight_layout()
plt.show()

# Evaluasi final
print("=== Final Evaluation on Test Set ===")
model.evaluate(X_test, y_test)

# Prediksi probabilitas dari model (output sigmoid, nilai 0–1)
y_pred_prob = model.predict(X_test)
# Konversi probabilitas ke label biner dengan threshold 0.5
# ≥0.5 = dysarthria (1), <0.5 = non-dysarthria (0)
y_pred      = (y_pred_prob >= 0.5).astype(int).flatten()

print(classification_report(y_test, y_pred, target_names=['non_dysarthria', 'dysarthria']))

"""### ROC Curve and AUC Score"""

plt.figure(figsize=(20,8))
fpr, tpr, _ = roc_curve(y_test,  y_pred)
auc = roc_auc_score(y_test, y_pred)
plt.plot(fpr,tpr,label="CNN Model, auc="+str(auc),lw=2)
plt.plot([0, 1], [0, 1], color="orange", lw=2, linestyle="--")
plt.legend(loc=4)
plt.show()

y_pred[y_pred>=0.5] = 1
y_pred[y_pred<0.5] = 0

sns.heatmap(confusion_matrix(y_test, y_pred),cmap='viridis',annot=True,fmt='.3g',
            xticklabels=['Non Dysarthria','Dysarthria'],yticklabels=['Non Dysarthria','Dysarthria'])
plt.xlabel('Predicted Class')
plt.ylabel('Actual Class')
plt.show()

"""### Classification Report"""

print(classification_report(y_test,y_pred))

print("Recall Score of the Model: ",recall_score(y_test,y_pred))

from google.colab import files
files.download('model.h5')
