# -*- coding: utf-8 -*-
"""KCV_Revisi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULKEe_RBh-bGQxa29WsYRwE7kwcSk33a

## **Automatic Detection of Dysarthria Using CNN on Acoustic Speech Data**

## IMPORT MODULES
"""

import kagglehub
import numpy as np
import pandas as pd
import os
import re
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import librosa
import librosa.display
import IPython.display as ipd
from sklearn.preprocessing import minmax_scale

# feature extraction
from tqdm import tqdm
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve, recall_score

# modelling CNN-GRU
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, Conv2D, MaxPooling2D, BatchNormalization, Reshape, GRU, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.metrics import AUC, Precision, Recall

plt.rcParams['figure.figsize'] = (20,8)
plt.rcParams['font.size'] = 16
sns.set_style('darkgrid')
warnings.filterwarnings("ignore")

"""## LOAD DATASET"""

path = kagglehub.dataset_download("iamhungundji/dysarthria-detection")
os.listdir(path + "/torgo_data")

df = pd.read_csv(path + "/torgo_data/data.csv")

df['filename'] = df['filename'].apply(lambda x: path + "/" + x)

print(f"Total samples: {len(df)}")
print(f"Columns      : {df.columns.tolist()}")
df.head()

"""## EDA"""

print(df.info())
print()
print(df.describe())

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Dysarthria label counts
df['is_dysarthria'].value_counts().plot(kind='bar', ax=axes[0], color=['steelblue','salmon'], edgecolor='black')
axes[0].set_title('Dysarthria Label Distribution')
axes[0].set_xlabel('Label')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=0)

# Gender counts
df['gender'].value_counts().plot(kind='bar', ax=axes[1], color=['mediumpurple','coral'], edgecolor='black')
axes[1].set_title('Gender Distribution')
axes[1].set_xlabel('Gender')
axes[1].set_ylabel('Count')
axes[1].tick_params(axis='x', rotation=0)

plt.suptitle('Dataset Overview', fontsize=18, fontweight='bold')
plt.tight_layout()
plt.show()

# Cross-tabulation: Gender × Label
cross = pd.crosstab(df['gender'], df['is_dysarthria'])
print(cross)

cross.plot(kind='bar', figsize=(8, 5), color=['steelblue','salmon'], edgecolor='black')
plt.title('Gender × Dysarthria Label')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.legend(title='Label')
plt.tight_layout()
plt.show()

# Per-group sample preview
groups = {
    'Male   – Dysarthria'    : df[(df['gender']=='male')   & (df['is_dysarthria']=='dysarthria')],
    'Female – Dysarthria'    : df[(df['gender']=='female') & (df['is_dysarthria']=='dysarthria')],
    'Male   – Non-Dysarthria': df[(df['gender']=='male')   & (df['is_dysarthria']=='non_dysarthria')],
    'Female – Non-Dysarthria': df[(df['gender']=='female') & (df['is_dysarthria']=='non_dysarthria')],
}

for name, subset in groups.items():
    print("=" * 55)
    print(f" {name}  (n={len(subset)})")
    print("=" * 55)
    display(subset.head(3))
    print()

"""## FEATURES"""

def show_waveplot(audio_path, label, gender):
    """Plot the time-domain waveform of an audio file."""
    x, sr = librosa.load(audio_path)
    plt.figure(figsize=(20, 6))
    librosa.display.waveshow(x, sr=sr)
    plt.title(f"Waveplot | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Time (s)")
    plt.ylabel("Amplitude")
    plt.tight_layout()
    plt.show()


def show_spectrogram(audio_path, label, gender):
    """Plot the short-time Fourier transform spectrogram (dB scale)."""
    x, sr = librosa.load(audio_path)
    X    = librosa.stft(x)
    Xdb  = librosa.amplitude_to_db(abs(X))
    plt.figure(figsize=(20, 6))
    librosa.display.specshow(Xdb, sr=sr, x_axis='time', y_axis='hz', cmap='plasma')
    plt.colorbar(format='%+2.0f dB')
    plt.title(f"Spectrogram | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.tight_layout()
    plt.show()


def show_zcr(audio_path, label, gender):
    """Plot the zero-crossing rate over time."""
    x, sr = librosa.load(audio_path)
    zcrs  = librosa.feature.zero_crossing_rate(x)
    total = librosa.zero_crossings(x).sum()
    print(f"Total zero crossings: {total}")
    plt.figure(figsize=(20, 5))
    plt.plot(zcrs[0], color='teal')
    plt.title(f"Zero Crossing Rate | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Frame")
    plt.ylabel("ZCR")
    plt.tight_layout()
    plt.show()

def show_spectral_centroids(audio_path, label, gender):
    """Plot spectral centroids overlaid on the waveform."""
    x, sr = librosa.load(audio_path)
    spectral_centroids = librosa.feature.spectral_centroid(y=x, sr=sr)[0]
    frames = range(len(spectral_centroids))
    t      = librosa.frames_to_time(frames)
    plt.figure(figsize=(20, 5))
    librosa.display.waveshow(x, sr=sr, alpha=0.4)
    plt.plot(t, normalize(spectral_centroids), color='r')
    plt.title(f"Spectral Centroids | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Time (s)")
    plt.ylabel("Normalized Centroid")
    plt.tight_layout()
    plt.show()


def show_spectral_rolloff(audio_path, label, gender):
    """Plot spectral rolloff overlaid on the waveform."""
    x, sr = librosa.load(audio_path)
    spectral_rolloff = librosa.feature.spectral_rolloff(y=x, sr=sr, roll_percent=0.01)[0]
    frames = range(len(spectral_rolloff))
    t      = librosa.frames_to_time(frames)
    plt.figure(figsize=(20, 5))
    librosa.display.waveshow(x, sr=sr, alpha=0.4)
    plt.plot(t, normalize(spectral_rolloff), color='r')
    plt.title(f"Spectral Rolloff | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Time (s)")
    plt.ylabel("Normalized Rolloff")
    plt.tight_layout()
    plt.show()


def show_mfccs(audio_path, label, gender):
    """Plot Mel-frequency cepstral coefficients (MFCCs)."""
    x, sr = librosa.load(audio_path)
    mfccs = librosa.feature.mfcc(y=x, sr=sr)
    plt.figure(figsize=(20, 6))
    librosa.display.specshow(mfccs, sr=sr, x_axis='time', cmap='plasma')
    plt.colorbar(format='%+2.0f')
    plt.title(f"MFCC | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Time (s)")
    plt.ylabel("MFCC Coefficient")
    plt.tight_layout()
    plt.show()


def show_melspectro(audio_path, label, gender):
    """Plot Mel spectrogram."""
    x, sr      = librosa.load(audio_path)
    melspectro = librosa.feature.melspectrogram(y=x, sr=sr)
    plt.figure(figsize=(20, 6))
    librosa.display.specshow(melspectro, sr=sr, x_axis='time', y_axis='mel', cmap='plasma')
    plt.colorbar(format='%+2.0f dB')
    plt.title(f"Mel Spectrogram | Class: {label}  |  Gender: {gender}", fontsize=16)
    plt.xlabel("Time (s)")
    plt.ylabel("Mel Frequency")
    plt.tight_layout()
    plt.show()

def normalize(x, axis=0):
    return minmax_scale(x, axis=axis)

sample_dys_female     = df[(df['is_dysarthria'] == 'dysarthria')     & (df['gender'] == 'female')].iloc[105]
sample_dys_male       = df[(df['is_dysarthria'] == 'dysarthria')     & (df['gender'] == 'male')].iloc[32]
sample_non_dys_female = df[(df['is_dysarthria'] == 'non_dysarthria') & (df['gender'] == 'female')].iloc[480]
sample_non_dys_male   = df[(df['is_dysarthria'] == 'non_dysarthria') & (df['gender'] == 'male')].iloc[0]

ipd.Audio(sample_dys_female['filename'])

ipd.Audio(sample_non_dys_female['filename'])

ipd.Audio(sample_dys_male['filename'])

ipd.Audio(sample_non_dys_male['filename'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_waveplot        (sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_spectrogram     (sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_zcr             (sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_spectral_centroids(sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_spectral_rolloff(sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_mfccs           (sample['filename'], sample['is_dysarthria'], sample['gender'])

for sample in [sample_dys_female, sample_non_dys_female, sample_dys_male, sample_non_dys_male]:
    print()
    print(f"Label: {sample['is_dysarthria']}  |  Gender: {sample['gender']}")
    show_melspectro      (sample['filename'], sample['is_dysarthria'], sample['gender'])

"""## FEATURES EXTRACTION"""

def feature_extraction(df):
    features = []
    valid_idx = []
    for i, record in tqdm(df.iterrows(), total=df.shape[0]):
        try:
            x, sr = librosa.load(record['filename'])
            mean_mfcc = np.mean(librosa.feature.mfcc(y=x, sr=sr, n_mfcc=128), axis=1)
            features.append(mean_mfcc)
            valid_idx.append(i)
        except EOFError:
            pass

    dataf = pd.DataFrame(features)
    dataf['class'] = df.loc[valid_idx, 'is_dysarthria'].values
    dataf['speaker_id'] = df.loc[valid_idx, 'filename'].str.extract(r'/(F[CM]\d+|MC\d+|FC\d+|M\d+|F\d+)_').values.flatten()
    return dataf

dataf = feature_extraction(df)

dataf

# Split
train_speakers = ['F03','F04','M02','M03','M05', 'FC02','FC03','MC01','MC03']
val_speakers   = ['M01','M04',                   'MC02','MC04']
test_speakers  = ['F01',                         'FC01']

train_df = dataf[dataf['speaker_id'].isin(train_speakers)]
val_df   = dataf[dataf['speaker_id'].isin(val_speakers)]
test_df  = dataf[dataf['speaker_id'].isin(test_speakers)]

# Encode label
for d in [train_df, val_df, test_df]:
    d['class'] = d['class'].map({'non_dysarthria': 0.0, 'dysarthria': 1.0})

X_train = train_df.iloc[:, :-2].values.reshape(-1, 16, 8, 1)
X_val   = val_df.iloc[:, :-2].values.reshape(-1, 16, 8, 1)
X_test  = test_df.iloc[:, :-2].values.reshape(-1, 16, 8, 1)

y_train = train_df['class'].values
y_val   = val_df['class'].values
y_test  = test_df['class'].values

print("Train:", X_train.shape, "| Val:", X_val.shape, "| Test:", X_test.shape)
print("Train label dist:", pd.Series(y_train).value_counts().to_dict())
print("Val label dist  :", pd.Series(y_val).value_counts().to_dict())
print("Test label dist :", pd.Series(y_test).value_counts().to_dict())

"""## MODELLING"""

model = Sequential([
    InputLayer(input_shape=(16, 8, 1)),

    Conv2D(32, (3, 3), activation='relu', padding="same"),
    BatchNormalization(),
    MaxPooling2D(2, 2),

    Conv2D(64, (3, 3), activation='relu', padding="same"),
    BatchNormalization(),
    MaxPooling2D(2, 2),

    Reshape((4, 128)),
    GRU(64, return_sequences=False),
    Dropout(0.3),

    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

# model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[
        'accuracy',
        AUC(name='auc'),
        Precision(name='precision'),
        Recall(name='recall')
    ]
)

model_name = "model.h5"
checkpoint = ModelCheckpoint(model_name,
                            monitor="val_loss",
                            mode="min",
                            save_best_only = True,
                            verbose=1)

earlystopping = EarlyStopping(monitor='val_loss',min_delta = 0, patience = 5, verbose = 1, restore_best_weights=True)

history = model.fit(X_train, y_train, epochs=50, validation_data=(X_val,y_val), callbacks=[checkpoint,earlystopping])

"""## Model Summary

### Learning Curves
"""

fig, axes = plt.subplots(1, 2, figsize=(20, 6))

axes[0].plot(history.history['loss'],     label='Train Loss')
axes[0].plot(history.history['val_loss'], label='Val Loss')
axes[0].set_title('Loss', fontsize=14)
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].legend()

axes[1].plot(history.history['accuracy'],     label='Train Accuracy')
axes[1].plot(history.history['val_accuracy'], label='Val Accuracy')
axes[1].set_title('Accuracy', fontsize=14)
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Accuracy')
axes[1].legend()

plt.tight_layout()
plt.show()

# Evaluasi final
print("=== Final Evaluation on Test Set ===")
model.evaluate(X_test, y_test)

# y_pred = model.predict(X_test)

y_pred_prob = model.predict(X_test)
y_pred      = (y_pred_prob >= 0.5).astype(int).flatten()

print(classification_report(y_test, y_pred, target_names=['non_dysarthria', 'dysarthria']))

"""### ROC Curve and AUC Score"""

plt.figure(figsize=(20,8))
fpr, tpr, _ = roc_curve(y_test,  y_pred)
auc = roc_auc_score(y_test, y_pred)
plt.plot(fpr,tpr,label="CNN Model, auc="+str(auc),lw=2)
plt.plot([0, 1], [0, 1], color="orange", lw=2, linestyle="--")
plt.legend(loc=4)
plt.show()

y_pred[y_pred>=0.5] = 1
y_pred[y_pred<0.5] = 0

sns.heatmap(confusion_matrix(y_test, y_pred),cmap='viridis',annot=True,fmt='.3g',
            xticklabels=['Non Dysarthria','Dysarthria'],yticklabels=['Non Dysarthria','Dysarthria'])
plt.xlabel('Predicted Class')
plt.ylabel('Actual Class')
plt.show()

"""### Classification Report"""

print(classification_report(y_test,y_pred))

print("Recall Score of the Model: ",recall_score(y_test,y_pred))

from google.colab import files
files.download('model.h5')